#!/bin/bash
TOOLS=`dirname $0`
VENV=$TOOLS/../.venv

virtualenv -q --clear --no-site-packages $VENV
pip install --upgrade -E $VENV -r $TOOLS/pip-requires
export PYTHONPATH=$VENV
python setup.py develop -d $VENV
rm -rf $VENV/../stacktester.egg-info
